### ISSUE TITLE
Broken link: "The way we work diagram"

### ISSUE THREAD

**Issue by AntoineAugusti** [cds-snc/guide-product-teams-equipes-produits#4]
The link to "The way we work diagram" points to a Slack message which has been deleted.

Is there a document somewhere?

https://github.com/cds-snc/guide-product-teams-equipes-produits/blob/1b4f3c55b2961114d9b83f809a54315218157dfb/_includes/navigation.html#L7

**Comment by wmoussa-gc** [comment]
Hi Antoine, the whole "ways of working" is being revamped, so I suggest we remove the broken link for now until a new diagram is created. Do you want to create a quick PR for it? I'll merge it.
